# ===============================================================
# utils/code_normalizer.py
# Converts plain ML scripts into standardized Optimizable classes
# ===============================================================

import ast
import json
from textwrap import indent
from pathlib import Path
from typing import Optional, List
from rich.console import Console

console = Console()


class CodeNormalizer:
    """
    Transforms a training script into an Optimizable-compatible class.
    Keeps sklearn / XGBoost / LightGBM logic intact.
    """

    def __init__(self, script_path: Path):
        self.script_path = script_path
        self.source = script_path.read_text()

    # -----------------------------------------------------------
    def transform_to_optimizable(self, class_name: str = "AutoGeneratedModel") -> Optional[str]:
        """Converts the script into an Optimizable-compatible structure."""
        try:
            tree = ast.parse(self.source)

            # 1️⃣ Extract hyperparameters
            params = self._extract_hyperparams(tree)
            default_hparams = {
                k: (v[0] if isinstance(v, list) and v else v)
                for k, v in params.items()
            }

            # 2️⃣ Extract AUC computation
            auc_block = self._extract_auc_block(tree)

            # 3️⃣ Build standardized Optimizable class
            new_code = self._build_class_code(class_name, default_hparams, auc_block)
            return new_code.strip()

        except Exception as ex:
            console.print(f"[red][CodeNormalizer][/red] Failed to transform {self.script_path.name}: {ex}")
            return None

    # -----------------------------------------------------------
    def _extract_hyperparams(self, tree: ast.AST) -> dict:
        """
        Extracts a hyperparameter dictionary (param_grid, param, params).
        Returns a dict mapping parameter names to lists or values.
        """
        params = {}

        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and any(
                        kw in target.id.lower() for kw in ["param", "grid", "search"]
                    ):
                        if isinstance(node.value, ast.Dict):
                            for key_node, val_node in zip(node.value.keys, node.value.values):
                                key = self._get_literal(key_node)
                                val = self._get_literal(val_node)
                                params[key] = val
        return params

    # -----------------------------------------------------------
    def _get_literal(self, node):
        """Converts AST literals safely into Python objects."""
        if isinstance(node, ast.Constant):
            return node.value
        elif isinstance(node, ast.Str):
            return node.s
        elif isinstance(node, ast.Num):
            return node.n
        elif isinstance(node, ast.List):
            return [self._get_literal(elt) for elt in node.elts]
        elif isinstance(node, ast.Tuple):
            return tuple(self._get_literal(elt) for elt in node.elts)
        elif isinstance(node, ast.NameConstant):
            return node.value
        else:
            try:
                return ast.unparse(node)
            except Exception:
                return str(node)

    # -----------------------------------------------------------
    def _extract_auc_block(self, tree: ast.AST) -> str:
        """Finds where AUC is computed or printed."""
        auc_lines = []
        lines = self.source.splitlines()

        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
                if "auc" in targets:
                    start, end = node.lineno - 1, getattr(node, "end_lineno", node.lineno)
                    auc_lines.extend(lines[start:end])

        if not auc_lines:
            # Fallback: try to find print(json.dumps())
            for line in lines:
                if "json.dumps" in line:
                    auc_lines.append(line)

        return "\n".join(auc_lines)

    def _build_class_code(self, class_name: str, default_hparams: dict, auc_block: str) -> str:
        """Constructs the final Optimizable class code."""
        body = self._strip_prints()

        # Split imports vs logic lines
        import_lines = []
        logic_lines = []
        for line in body.splitlines():
            if line.strip().startswith("import ") or line.strip().startswith("from "):
                import_lines.append(line)
            else:
                logic_lines.append(line)

        # Join separately
        imports_block = "\n".join(import_lines)
        logic_block = "\n".join(logic_lines)

        # -------------------------------------------------------
        # 🧹 Remove AUC lines from logic_block to avoid duplicates
        # -------------------------------------------------------
        cleaned_logic_lines = []
        for line in logic_block.splitlines():
            if any(k in line for k in ["roc_auc_score", "auc", "json.dumps"]):
                continue
            cleaned_logic_lines.append(line)
        logic_block = "\n".join(cleaned_logic_lines)

        # Indent properly
        auc_block = indent(auc_block.strip(), " " * 12)
        logic_block = indent(logic_block.strip(), " " * 8)

        # -------------------------------------------------------
        # Build final class code
        # -------------------------------------------------------
        class_code = f"""import json
import pandas as pd
from sklearn.model_selection import train_test_split
from examples.contract import Optimizable, Hyperparameters, Metrics

{imports_block}

class {class_name}(Optimizable):
    \"\"\"Auto-generated Optimizable class.\"\"\"
    DEFAULT_HPARAMS: Hyperparameters = {json.dumps(default_hparams, indent=4)}

    def run(self, hparams: Hyperparameters) -> Metrics:
        import warnings, os
        os.environ['PYTHONWARNINGS'] = 'ignore'
        warnings.filterwarnings('ignore')

        df = self.data.copy()
{logic_block}

{auc_block}
        return {{"auc": float(auc)}}

if __name__ == "__main__":
    data = pd.read_csv("data/train.csv")
    script = {class_name}(data)
    print(script.run(hparams={class_name}.DEFAULT_HPARAMS))
"""
        return class_code



    # -----------------------------------------------------------
    def _strip_prints(self) -> str:
        """Removes print statements from the source code."""
        return "\n".join(
            line for line in self.source.splitlines()
            if not line.strip().startswith("print(")
        )


# ===============================================================
# 🧩 High-level function to normalize a list of scripts
# ===============================================================
def normalize_scripts(scripts: List[str]) -> List[str]:
    """
    Normalizes all scripts into the Optimizable class format.
    Automatically uses LLM fallback if AST transformation fails.
    Returns a list of valid script paths ready for optimization.
    """

    normalized_scripts = []

    for script_path in scripts:
        path = Path(script_path)
        text = path.read_text()

        # Skip if already Optimizable
        if "class" in text and "Optimizable" in text:
            console.print(f"[blue]ℹ️ {path.name} already in Optimizable format.[/blue]")
            normalized_scripts.append(str(path))
            continue

        console.print(f"[cyan]🔧 Normalizing {path.name}...[/cyan]")
        normalizer = CodeNormalizer(path)
        normalized_code = normalizer.transform_to_optimizable("AutoGeneratedModel")

        normalized_path = path.with_name(f"{path.stem}_optimizable.py")
        normalized_path.write_text(normalized_code)
        normalized_scripts.append(str(normalized_path))
        console.print(f"[green]✅ Normalized script saved as {normalized_path.name}[/green]")

    return normalized_scripts
