# ===============================================================
# utils/code_normalizer.py
# Converts plain ML scripts into standardized Optimizable classes
# ===============================================================

import ast
import json
import os
import re
import requests
from textwrap import indent
from pathlib import Path
from typing import Optional, List
from rich.console import Console

console = Console()


class CodeNormalizer:
    """Transforms a training script into an Optimizable-compatible class."""

    def __init__(self, script_path: Path):
        self.script_path = script_path
        self.source = script_path.read_text()

    def transform_to_optimizable(self, class_name: str = "AutoGeneratedModel") -> Optional[str]:
        """Converts the script into an Optimizable-compatible structure."""
        try:
            tree = ast.parse(self.source)
            params = self._extract_hyperparams(tree)
            default_hparams = {k: (v[0] if isinstance(v, list) and v else v) for k, v in params.items()}
            auc_block = self._extract_auc_block(tree)
            new_code = self._build_class_code(class_name, default_hparams, auc_block)
            return new_code.strip()
        except Exception as ex:
            console.print(f"[red]CodeNormalizer failed for {self.script_path.name}: {ex}[/red]")
            return None

    def _extract_hyperparams(self, tree: ast.AST) -> dict:
        params = {}
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and any(kw in target.id.lower() for kw in ["param", "grid", "search"]):
                        if isinstance(node.value, ast.Dict):
                            for key_node, val_node in zip(node.value.keys, node.value.values):
                                key = self._get_literal(key_node)
                                val = self._get_literal(val_node)
                                params[key] = val
        return params

    def _get_literal(self, node):
        if isinstance(node, ast.Constant):
            return node.value
        elif isinstance(node, ast.List):
            return [self._get_literal(e) for e in node.elts]
        elif isinstance(node, ast.Tuple):
            return tuple(self._get_literal(e) for e in node.elts)
        else:
            try:
                return ast.unparse(node)
            except Exception:
                return str(node)

    def _extract_auc_block(self, tree: ast.AST) -> str:
        auc_lines = []
        lines = self.source.splitlines()
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign):
                targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
                if "auc" in targets:
                    start, end = node.lineno - 1, getattr(node, "end_lineno", node.lineno)
                    auc_lines.extend(lines[start:end])
        if not auc_lines:
            for line in lines:
                if "json.dumps" in line:
                    auc_lines.append(line)
        return "\n".join(auc_lines)

    def _build_class_code(self, class_name: str, default_hparams: dict, auc_block: str) -> str:
        body = self._strip_prints()
        cleaned_logic_lines = []
        for line in body.splitlines():
            s = line.strip()
            if s.startswith(("import ", "from ")):
                cleaned_logic_lines.append(line)
                continue
            if re.match(r"^\s*auc\s*=", line) or ("json.dumps" in line and "auc" in line):
                continue
            cleaned_logic_lines.append(line)

        logic_block = indent("\n".join(cleaned_logic_lines).strip(), " " * 8)
        auc_block = indent(auc_block.strip(), " " * 8)

        return f"""import json
import pandas as pd
from sklearn.model_selection import train_test_split
from examples.contract import Optimizable, Hyperparameters, Metrics

class {class_name}(Optimizable):
    \"\"\"Auto-generated Optimizable class.\"\"\"
    DEFAULT_HPARAMS: Hyperparameters = {json.dumps(default_hparams, indent=4)}

    def run(self, hparams: Hyperparameters) -> Metrics:
        import warnings, os
        os.environ['PYTHONWARNINGS'] = 'ignore'
        warnings.filterwarnings('ignore')
        df = self.data.copy()
{logic_block}

{auc_block}
        return {{"auc": float(auc)}}

if __name__ == "__main__":
    data = pd.read_csv("data/train.csv")
    script = {class_name}(data)
    print(script.run(hparams={class_name}.DEFAULT_HPARAMS))
"""

    def _strip_prints(self) -> str:
        return "\n".join(l for l in self.source.splitlines() if not l.strip().startswith("print("))


# ===============================================================
# Normalization Entry Point
# ===============================================================

LLM_PROMPT_TEMPLATE = """
You are an AutoML Python engineer.

Your task is to rewrite the following plain training script into a self-contained
Optimizable Python module that follows this contract structure:

───────────────────────────────────────────────────────────────
# <dataset>_baseline.py
\"\"\"A simple, optimizable baseline script.\"\"\"
import pandas as pd
from typing import Dict, Any
from examples.contract import Optimizable, DataFrame, Hyperparameters, Metrics

class <CustomName>(Optimizable):
    \"\"\"An optimizable script for the dataset.\"\"\"

    DEFAULT_HPARAMS: Hyperparameters = {{
        # default hyperparameters here
    }}

    def run(self, hparams: Hyperparameters) -> Metrics:
        \"\"\"Runs the training and evaluation pipeline.\"\"\"
        df = self.data.copy()
        # full pipeline (preprocessing, model, training, eval)
        auc = ...
        return {{'auc': auc}}

if __name__ == '__main__':
    data = pd.read_csv('data/train.csv')
    script = <CustomName>(data)
    baseline_metrics = script.run(hparams=<CustomName>.DEFAULT_HPARAMS)
    print(f"Baseline Run Metrics: {{baseline_metrics}}")
───────────────────────────────────────────────────────────────

Rewrite rules:
1. Wrap the given ML training code into a class that inherits from Optimizable.
2. Preserve all preprocessing, model, and parameter logic from the original script.
3. Add DEFAULT_HPARAMS based on parameter grid or model defaults.
4. Implement run(self, hparams: Hyperparameters) that returns {{'auc': auc}}.
5. Ensure the script runs directly via `if __name__ == '__main__'`.

Code quality requirements:
- Always import all libraries that are used. If any function references a namespace
  like `sklearn.something`, ensure `import sklearn` is present at the top.
- Do not invent or use non-existent models or classes. Use only valid models from:
  scikit-learn, XGBoost, or LightGBM.
- Use explicit imports whenever possible (e.g., `from sklearn.linear_model import LogisticRegression`).
- The code must be executable without undefined names or missing imports.
- The script must produce an AUC metric named exactly `auc` and return it as a float.
- Avoid any print statements inside `run()`. Only print in the main block.
- No markdown, explanations, or extra text — output only valid Python code.

--- SCRIPT START ---
{script_text}
--- SCRIPT END ---
"""


def normalize_scripts(scripts: List[str], llm: bool = False) -> List[str]:
    """
    Normalizes scripts into the Optimizable class format.
    - If llm=True, uses GPT-5 API rewrite only.
    - If llm=False, uses the standard AST-based CodeNormalizer only.
    """
    normalized = []
    api_key = os.getenv("GPT5_API_KEY")
    api_url = "https://api.openai.com/v1/chat/completions"

    for script_path in scripts:
        path = Path(script_path)
        text = path.read_text()

        if "class" in text and "Optimizable" in text:
            console.print(f"{path.name} already normalized.")
            normalized.append(str(path))
            continue

        console.print(f"Normalizing {path.name}...")

        # ==============================================================
        # LLM Mode (GPT-5 only)
        # ==============================================================
        if llm:
            if not api_key:
                console.print(f"Error: GPT5_API_KEY not set. Skipping {path.name}.")
                continue

            headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            payload = {
                "model": "gpt-5",
                "messages": [
                    {"role": "system", "content": "You are an expert AutoML Python engineer."},
                    {"role": "user", "content": LLM_PROMPT_TEMPLATE.format(script_text=text)},
                ],
            }

            try:
                r = requests.post(api_url, headers=headers, json=payload)
                r.raise_for_status()
                llm_code = r.json()["choices"][0]["message"]["content"]

                out_path = path.with_name(f"{path.stem}_optimizable.py")
                out_path.write_text(llm_code)
                normalized.append(str(out_path))
                console.print(f"Saved {out_path.name}")
            except Exception as e:
                console.print(f"GPT-5 normalization failed for {path.name}: {e}")
            continue

        # ==============================================================
        # Standard Mode (AST transformation only)
        # ==============================================================
        normalizer = CodeNormalizer(path)
        normalized_code = normalizer.transform_to_optimizable("AutoGeneratedModel")

        if not normalized_code:
            console.print(f"Standard normalization failed for {path.name}.")
            continue

        out_path = path.with_name(f"{path.stem}_optimizable.py")
        out_path.write_text(normalized_code)
        normalized.append(str(out_path))
        console.print(f"Saved {out_path.name}")

    return normalized
